# Generated by Django 4.1.5 on 2023-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('height', models.CharField(max_length=250)),
                ('mass', models.CharField(max_length=250)),
                ('hair_color', models.CharField(max_length=250)),
                ('skin_color', models.CharField(max_length=250)),
                ('eye_color', models.CharField(max_length=250)),
                ('birth_year', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('homeworld', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
