# Generated by Django 4.1.5 on 2023-01-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0006_rename_download_date_dataset_downloaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='edited',
            field=models.CharField(default='', max_length=250),
        ),
    ]
